---
title: "iseder_HW_7"
author: "Izzy Sederbaum"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::html_document2:
    theme: cosmo
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(haven)
library(tidyverse)
library(readstata13)
library(kableExtra)
```



```{r read in data + labels}

addhealth <- read_dta("C:/Users/iseder/OneDrive - UW/Year 2/Winter 2021/CSDE 502/Add_Health_Wave1_All_stata12.dta")


#dataset label
attributes(addhealth)$label
#variable label (this is visible in the viewer too)
attributes(addhealth$AID)$label

#look through dataset for variables to keep

ahcomplete_metadata <- bind_cols(
    varname = colnames(addhealth),
    varlabel = addhealth %>% map(~ attributes(.)$label) %>% unlist()
)

DT::datatable(ahcomplete_metadata)
```


## Variable Selection

For this homework, I will be looked at sex, self-rated happiness, hours of sleep gotten per night and household income.
```{r select variables}
addhealth <- addhealth %>% 
  select (aid, bio_sex, h1fs11, pa55) %>% 
  rename(ID  = aid, 
         sex = bio_sex, 
         happy = h1fs11, 
         family_income = pa55)
```


```{r recode variables}
addhealth <-addhealth %>% 
  mutate(family_income = case_when(as.numeric(family_income) > 999 ~ NA_real_, 
                                   TRUE ~ as.numeric(family_income))) 
  
income_quants <- quantile(x = addhealth$family_income, probs = c(0.10, .25, .50,.75, .90), na.omit(addhealth$family_income))
  
addhealth <- addhealth %>% 
  mutate(income_cat = cut(x = family_income, breaks = c(0, income_quants,999), 
                                             labels = c("0-10","11-25", "25-49", "50-75", "76-90", "91-100"), 
                                             include.lowest = TRUE) %>% 
         factor(ordered = TRUE))  

attributes(addhealth$income_cat)$label<-"family income categories"


addhealth <-addhealth %>% 
  mutate(sex = case_when(sex == 1 ~ "female", 
                         sex == 2 ~ "male", 
                         sex == 6 | sex == 8 ~ "unknown", 
                         TRUE ~ "unknown"))

attributes(addhealth$sex)$label<-"sex"

addhealth <-addhealth %>% 
  mutate(happy = case_when(happy == 0 ~ "never or rarely", 
                           happy == 1 ~ "sometimes",
                           happy == 2 ~ "a lot of the time", 
                           happy == 3 ~ "most or all of the time",
                           happy == 6 | happy == 8 ~ "unknown", 
                           TRUE ~"unknown") %>% 
           factor(ordered = TRUE)) 

attributes(addhealth$happy)$label<-"In the past week, you felt happy"



```

Here, we look a the distribution of family income, sex, and happiness:

```{r tables}
addhealth %>% 
    group_by(income_cat) %>% 
    summarise(n = n()) %>% 
    mutate(`%` = n / sum(n) * 100) %>% 
    mutate(`%` = `%` %>% round(1)) %>% 
    kable() %>% 
    kable_styling(full_width = FALSE, position = "left")


addhealth %>% 
    group_by(sex) %>% 
    summarise(n = n()) %>% 
    mutate(`%` = n / sum(n) * 100) %>% 
    mutate(`%` = `%` %>% round(1)) %>% 
    kable() %>% 
    kable_styling(full_width = FALSE, position = "left")


addhealth %>% 
    group_by(happy) %>% 
    summarise(n = n()) %>% 
    mutate(`%` = n / sum(n) * 100) %>% 
    mutate(`%` = `%` %>% round(1)) %>% 
    kable() %>% 
    kable_styling(full_width = FALSE, position = "left")


```

The table below displays happiness vs. family income:

```{r happiness-income}
addhealth %>% 
    group_by(income_cat,
             happy) %>% 
    summarise(n = n())  %>% 
    mutate(`%` = n / sum(n) * 100) %>% 
    mutate(`%` = `%` %>% round(1)) %>% 
    kable() %>% 
    kable_styling(full_width = FALSE, position = "left")
```

Here, we see self-rated happiness by sex: 
```{r graph}
ggplot(data = addhealth,
       aes(x = happy, fill = sex)) +
  geom_bar(position = position_dodge()) +
  xlab("Self-rated Happiness") +
  ylab("Count") +
  theme_classic() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) + 
    ggtitle("Self-rated Student Happiness by Sex", subtitle = "National Longitudinal Study of Adolescent Health (Wave 1)")
          
```


```{r label}
attributes(addhealth)$label <- "Variables Sex, Family Income, and Happiness from the National Longitudinal Study of Adolescent Health (Wave 1)"
```

## Source Code

```{r}
cat(readLines("iseder_HW3.Rmd"), sep = '\n')
